spring:
  profiles:
    active: dev
---
server:
  port: 8083
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.codelete.shareboot.vo       # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
spring:
  profiles: product
  messages:
    basename: i18n/Messages,i18n/Pages
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/shareboot      # 数据库连接地址
    username: root                                  # 数据库用户名
    password: root                                  # 数据库连接密码
    filters: stat,wall,log4j
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  redis:
    host: 192.168.1.122
    port: 6379
    password: shareboot
    timeout: 1000
    database: 0
    pool:
      max-active: 10
      max-idle: 8
      min-idle: 2
      max-wait: 100
    redis-two:
        host: 192.168.1.122
        port: 6380
        password: shareboot
        timeout: 1000
        database: 0
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2
          max-wait: 100
    mail:
      host: smtp.qq.com
      username: 893690586@qq.com
      password: xxxxx
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
        mail.smtp.starttls.required: true
http:
    multipart:
      enabled: true     # 可以启用http上传
      max-file-size: 10MB  # 设置支持的单个上传文件的大小限制
      max-request-size: 20MB # 设置最大的请求的文件大小，设置总体大小请求
      file-size-threshold: 512KB   # 当上传文件达到指定配置量的时候会将文件内容写入磁盘
      location: /       # 设置上传的临时目录
---
server:
  port: 8082
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.codelete.shareboot.vo       # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
spring:
  profiles: test
  messages:
    basename: i18n/Messages,i18n/Pages
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/shareboot      # 数据库连接地址
    username: root                                  # 数据库用户名
    password: root                                  # 数据库连接密码
    filters: stat,wall,log4j
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  redis:
    host: 192.168.1.122
    port: 6379
    password: shareboot
    timeout: 1000
    database: 0
    pool:
      max-active: 10
      max-idle: 8
      min-idle: 2
      max-wait: 100
    redis-two:
        host: 192.168.1.122
        port: 6380
        password: shareboot
        timeout: 1000
        database: 0
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2
          max-wait: 100
    mail:
      host: smtp.qq.com
      username: 893690586@qq.com
      password: xxxxx
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
        mail.smtp.starttls.required: true
http:
    multipart:
      enabled: true     # 可以启用http上传
      max-file-size: 10MB  # 设置支持的单个上传文件的大小限制
      max-request-size: 20MB # 设置最大的请求的文件大小，设置总体大小请求
      file-size-threshold: 512KB   # 当上传文件达到指定配置量的时候会将文件内容写入磁盘
      location: /       # 设置上传的临时目录
---
server:
  port: 8081
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.codelete.shareboot.vo       # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
spring:
  profiles: dev
  messages:
    basename: i18n/Messages,i18n/Pages
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/shareboot      # 数据库连接地址
    username: root                                  # 数据库用户名
    password: root                                  # 数据库连接密码
    filters: stat,wall,log4j
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  redis:
    host: 192.168.1.122
    port: 6379
    password: shareboot
    timeout: 1000
    database: 0
    pool:
      max-active: 10
      max-idle: 8
      min-idle: 2
      max-wait: 100
    redis-two:
        host: 192.168.1.122
        port: 6380
        password: shareboot
        timeout: 1000
        database: 0
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2
          max-wait: 100
    mail:
      host: smtp.qq.com
      username: 893690586@qq.com
      password: xxxxx
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
        mail.smtp.starttls.required: true
http:
    multipart:
      enabled: true     # 可以启用http上传
      max-file-size: 10MB  # 设置支持的单个上传文件的大小限制
      max-request-size: 20MB # 设置最大的请求的文件大小，设置总体大小请求
      file-size-threshold: 512KB   # 当上传文件达到指定配置量的时候会将文件内容写入磁盘
      location: /       # 设置上传的临时目录
    